#!/usr/bin/env bash
# Installs nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo bash -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i "s#server_name _;#server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;#" /etc/nginx/sites-enabled/default
sudo service nginx restart
