#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get -y install nginx
sudo bash -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i "s#server_name _;#server_name _;\n\tadd_header X-Served-By $(hostname);#" /etc/nginx/sites-available/default
sudo service nginx restart
