#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID, Displays To infinity and beyond indefinitely, Displays I hate the kill command when receiving a SIGTERM signal, Displays Y U no love me?! when receiving a SIGINT signal, Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pid=$(pgrep -f 100-process_and_pid_file)
echo "$pid" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && rm -f "/var/run/myscript.pid" && exit' SIGTERM SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
done
