#!/usr/bin/env bash
# Fixes the container so that Nginx is running as the nginx user.
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/\b80\b/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
