#!/usr/bin/env bash
# Runs nginx as nginx user.
sudo service nginx stop
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/\b80\b/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
